// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE6PtuSUK3gtH9h00mU1Rr7IYEG_ubYeQ',
    appId: '1:829960733697:web:5554afdf4364857541ac00',
    messagingSenderId: '829960733697',
    projectId: 'flutter-final-project-nc',
    authDomain: 'flutter-final-project-nc.firebaseapp.com',
    storageBucket: 'flutter-final-project-nc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpokkCe1JvvOhyr6WZtbdvNgkh0bUgHL8',
    appId: '1:829960733697:android:3ce8d42543dd906e41ac00',
    messagingSenderId: '829960733697',
    projectId: 'flutter-final-project-nc',
    storageBucket: 'flutter-final-project-nc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdivuQfn39bepfhjQG6MbfZ622iZgA5io',
    appId: '1:829960733697:ios:78dc9e6dd6fab67841ac00',
    messagingSenderId: '829960733697',
    projectId: 'flutter-final-project-nc',
    storageBucket: 'flutter-final-project-nc.appspot.com',
    iosBundleId: 'com.example.flutterFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdivuQfn39bepfhjQG6MbfZ622iZgA5io',
    appId: '1:829960733697:ios:6a6af7766faa402e41ac00',
    messagingSenderId: '829960733697',
    projectId: 'flutter-final-project-nc',
    storageBucket: 'flutter-final-project-nc.appspot.com',
    iosBundleId: 'com.example.flutterFinalProject.RunnerTests',
  );
}
